include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.gr.dart
    - lib/**.g.dart
    - lib/**.gen.dart
    - test/**.mocks.dart
    - lib/**.config.dart
    - lib/generated_plugin_registrant.dart
    - lib/**.mocks.dart
    - actions-runner
  errors:
    todo: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore

linter:
  rules:
    require_trailing_commas: false
    depend_on_referenced_packages: false
    always_use_package_imports: false